# Generated by Django 6.0.7 on 2026-07-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_genre_movie_language_movie_release_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.DecimalField(db_index=True, decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="theater",
            name="time",
            field=models.DateTimeField(db_index=True),
        ),
    ]
