# Generated by Django 6.1 on 2026-08-18 22:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_seatreservation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razorpay_event_id", models.CharField(max_length=100, unique=True)),
                ("event_type", models.CharField(max_length=50)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="theater",
            name="screen",
            field=models.CharField(blank=True, default="Screen 1", max_length=50),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razorpay_order_id", models.CharField(max_length=100, unique=True)),
                (
                    "razorpay_payment_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "razorpay_signature",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("amount_rupees", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_paise", models.PositiveBigIntegerField()),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("attempted", "Attempted"),
                            ("success", "Success (Captured & Fulfilled)"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            (
                                "success_unfulfilled",
                                "Success (Unfulfilled - Refund Required)",
                            ),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                        ],
                        default="created",
                        max_length=25,
                    ),
                ),
                (
                    "refund_status",
                    models.CharField(
                        choices=[
                            ("not_applicable", "Not Applicable"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("partial", "Partial"),
                        ],
                        default="not_applicable",
                        max_length=20,
                    ),
                ),
                (
                    "refunded_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("seat_snapshot", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="movies.movie",
                    ),
                ),
                (
                    "theater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="movies.theater",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="movies.payment",
            ),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "booking_reference",
                    models.CharField(
                        blank=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("snapshot_movie_name", models.CharField(max_length=255)),
                ("snapshot_theater_name", models.CharField(max_length=255)),
                ("snapshot_screen", models.CharField(blank=True, max_length=50)),
                ("snapshot_show_time", models.DateTimeField()),
                ("snapshot_seat_numbers", models.JSONField(default=list)),
                (
                    "snapshot_amount_rupees",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "snapshot_payment_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "email_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "email_status_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("email_attempts", models.PositiveIntegerField(default=0)),
                ("emailed_at", models.DateTimeField(blank=True, null=True)),
                ("last_email_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket",
                        to="movies.payment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="movies_paym_status_5316c9_idx"),
        ),
    ]
